---
- name: Create a File with Ansible
  hosts: localhost
  tasks:
    - name: Create example.txt
      file:
        path: /tmp/example.txt
        state: touch
      become: true

    - name: Get localhost IP address
      debug:
        msg: "The IP address of localhost is {{ ansible_facts['default_ipv4']['address'] }}"
      when: "'default_ipv4' in ansible_facts"
