---
- name: Create a File with Ansible
  hosts: localhost
  tasks:
    - name: Create example.txt
      file:
        path: /tmp/example.txt
        state: touch
      become: true

    - name: Get localhost IP address
      shell: hostname -I
      register: ip_address_result

    - name: Display IP address
      debug:
        var: ip_address_result.stdout
