---
- name: Create a File with Ansible
  hosts: localhost # Targeting the localhost
  tasks:
    - name: Create example.txt
      file:
        path: /tmp/example.txt
        state: touch
      become: true # To run the task with sudo privileges
